CREATE TABLE IF NOT EXISTS users
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email           VARCHAR NOT NULL,
    password        VARCHAR NOT NULL,
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    email_verified  BOOLEAN NOT NULL DEFAULT FALSE,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT users_email_unique UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS workspaces
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR NOT NULL,
    description     TEXT,
    status          VARCHAR NOT NULL DEFAULT 'active',
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT workspaces_status_check
        CHECK (status IN ('active', 'suspended', 'archived'))
);

CREATE TABLE IF NOT EXISTS subscriptions
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku             VARCHAR NOT NULL,
    name            VARCHAR NOT NULL,
    billing_cycle   VARCHAR NOT NULL,
    trial_days      INTEGER NOT NULL DEFAULT 0,
    user_capacity   INTEGER NOT NULL DEFAULT 1,
    price_display   NUMERIC(12, 2) NOT NULL,
    price_actual    NUMERIC(12, 2) NOT NULL,
    currency        CHAR(3) NOT NULL DEFAULT 'USD',
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT subscriptions_sku_unique UNIQUE (sku),

    CONSTRAINT subscriptions_billing_cycle_check
        CHECK (billing_cycle IN ('monthly', 'yearly', 'lifetime')),

    CONSTRAINT subscriptions_trial_days_check
        CHECK (trial_days >= 0),

    CONSTRAINT subscriptions_user_capacity_check
        CHECK (user_capacity > 0),

    CONSTRAINT subscriptions_price_check
        CHECK (price_actual >= 0 AND price_display >= 0),

    CONSTRAINT subscriptions_currency_check
        CHECK (char_length(currency) = 3)
);

CREATE TABLE IF NOT EXISTS workspace_users
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id    BIGINT NOT NULL,
    user_id         BIGINT NOT NULL,
    role            VARCHAR NOT NULL DEFAULT 'member',
    joined_at       TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT workspace_users_role_check
        CHECK (role IN ('owner', 'admin', 'member')),

    CONSTRAINT workspace_users_unique
        UNIQUE (workspace_id, user_id),

    CONSTRAINT workspace_users_workspace_fk
        FOREIGN KEY (workspace_id)
            REFERENCES workspaces (id)
            ON DELETE CASCADE,

    CONSTRAINT workspace_users_user_fk
        FOREIGN KEY (user_id)
            REFERENCES users (id)
            ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS workspace_subscriptions
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id        BIGINT NOT NULL,
    subscription_id     BIGINT NOT NULL,
    billing_cycle       VARCHAR NOT NULL,
    status              VARCHAR NOT NULL DEFAULT 'active',
    started_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at          TIMESTAMPTZ,
    canceled_at         TIMESTAMPTZ,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT workspace_subscriptions_workspace_unique
        UNIQUE (workspace_id),

    CONSTRAINT workspace_subscriptions_billing_cycle_check
        CHECK (billing_cycle IN ('monthly', 'yearly', 'lifetime')),

    CONSTRAINT workspace_subscriptions_status_check
        CHECK (status IN ('active', 'trial', 'expired', 'canceled')),

    CONSTRAINT workspace_subscriptions_dates_check
        CHECK (
            expires_at IS NULL
                OR expires_at > started_at
            ),

    CONSTRAINT workspace_subscriptions_workspace_fk
        FOREIGN KEY (workspace_id)
            REFERENCES workspaces (id)
            ON DELETE CASCADE,

    CONSTRAINT workspace_subscriptions_subscription_fk
        FOREIGN KEY (subscription_id)
            REFERENCES subscriptions (id)
);

CREATE INDEX idx_workspace_users_workspace_id
    ON workspace_users (workspace_id);

CREATE INDEX idx_workspace_users_user_id
    ON workspace_users (user_id);

CREATE INDEX idx_workspace_subscriptions_subscription_id
    ON workspace_subscriptions (subscription_id);

