CREATE TABLE IF NOT EXISTS users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(255) NOT NULL,
    email    VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS addresses
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    street  VARCHAR(255) NOT NULL,
    city    VARCHAR(255) NOT NULL,
    zip     VARCHAR(50) NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT addresses_users_id_fk FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT addresses_user_unique UNIQUE (user_id, street, city, zip)
);